#!/usr/bin/env bash

length=${1:-1MB}
nproc=${2:-1}

( time -p mylofreq -p ${nproc} -r $REFSEQ \
    -1 $length/Common_7_NeuN_DO16090243-final-all-$length.bam \
    -2 $length/Fibro_Common_7_DO16090243-final-all-$length.bam \
    -t Somatic -d $DBSNP_ALL \
    -o $length/${nproc}proc/ ) 1>&$length/${nproc}proc/lofreqSomatic-run.time &
