#!/usr/bin/env bash

echo length,numcores,caller,runtime

for caller in strelka2{Somatic,Germline} Tnseq lofreq{Somatic,Germline}; do
    # various length
    for length in {1,3,10,30,100}MB wgs; do
        ./parse-run-time $length 6 $caller
    done
    # various number of cores
    for nproc in 1 2 4 12; do
        ./parse-run-time 1MB $nproc $caller
        ./parse-run-time 10MB $nproc $caller
    done
done
