---
layout: default
---

Hello, World!

```{r echo=FALSE, warning=FALSE, message=FALSE}
library(lme4)
library(lattice)
library(VennDiagram)
opts_chunk$set(dpi = 144)
opts_chunk$set(out.width = "600px")
opts_chunk$set(dev = c("png", "pdf"))
lattice.options(default.args = list(as.table = TRUE))
lattice.options(default.theme = "standard.theme")
source("../../src/mybcftools.R")
```

```{r engine="bash", eval=FALSE}
cd $HOME/projects/bsm/results/2018-05-09-truth-sets
mkdir -p chr22/S1
for vcf in S1/NA128*.vcf.gz; do bcftools view --output-file chr22/$vcf --output-type z --targets chr22 --apply-filters .,PASS $vcf; done
# filter truth sets
./filter-ceph-grandp-vcfs chr22/S1 snps
indir=/big/results/bsm/2018-03-20-benchmark-testdata/wgs/vcf/snvs
outdir=chr22/S1-snps
# filter test set (of each caller) for chr22 and default PASS
for caller in lofreqSomatic  somaticSniper  strelka2Germline  strelka2Somatic  Tnseq; do
    bcftools view --output-type z --output-file $outdir/$caller.vcf.gz --targets 22 --apply-filters .,PASS $indir/$caller.vcf.gz
    bcftools index --tbi $outdir/$caller.vcf.gz
done
cd chr22
# take intersections
for caller in lofreqSomatic  somaticSniper  strelka2Germline  strelka2Somatic  Tnseq; do
    ../isec-ceph-grandp S1-snps/$caller.vcf.gz snps S1
done
```

```{r engine="bash", eval=TRUE}
cd /big/results/bsm/2018-05-09-truth-sets/chr22/check-chaggai/attila
# remove 5th column (Tnseq-specific info)
mybcftools-isec-tsv [01][01][01][01] | cut -f1-4,6- > all.tsv
```

```{r ceph4-venn}
tsv <- "/big/results/bsm/2018-05-09-truth-sets/chr22/check-chaggai/attila/all.tsv"
l <- import.mybcftools.isec.tsv(tsv, gpnames <- paste0("NA128", 89:92))
my.par <- list(main.cex = 1.8, fill = trellis.par.get("superpose.line")$col[1:5], col = "gray", cat.cex = 1.4)
grid.draw(venn.diagram(l, NULL, main.cex = my.par$main.cex, fill = my.par$fill[2:5], cat.cex = my.par$cat.cex))
```

```{r engine="bash", eval=TRUE}
for caller in lofreqSomatic  somaticSniper  strelka2Germline  strelka2Somatic  Tnseq; do
    cd /big/results/bsm/2018-05-09-truth-sets/chr22/$caller-snps; mybcftools-isec-tsv [01][01][01][01][01] > all.tsv
done
```

```{r Tnseq-ceph4-venn}
draw5 <- function(caller, par = my.par) {
    tsv <- paste0("/big/results/bsm/2018-05-09-truth-sets/chr22/", caller, "-snps/all.tsv")
    l <- import.mybcftools.isec.tsv(tsv, gpnames <- c(caller, gpnames))
    grid.draw(venn.diagram(l, NULL, main.cex = par$main.cex, fill = par$fill, cat.cex = par$cat.cex))
}
draw5("Tnseq")
```

```{r strelka2Somatic-ceph4-venn}
draw5("strelka2Somatic")
```

```{r strelka2Germline-ceph4-venn}
draw5("strelka2Germline")
```

## Checking varied positions vs Chaggai's

```{r engine="bash", eval=FALSE}
cd $HOME/projects/bsm/results/2018-05-09-truth-sets/chr22
mkdir -p check-chaggai/{attila,chaggai}
ls -1 Tnseq-snps | sed 's/.\(....\)/\1/' |
    for part in `cat`; do cat Tnseq-snps/0$part Tnseq-snps/1$part > check-chaggai/attila/$part; done
cat check-chaggai/attila/[01][01][01][01] | cut -f2 | sort -u > check-chaggai/attila/ceph-gp-var.pos
cut -f2 $HOME/projects/bsm/results/Chaggai-Benchmark_NG_Jan2018/Chr22/Chr22.Final.output.txt |
    sort -u > check-chaggai/chaggai/ceph-gp-var.pos
```

```{r chaggai-attila-var-pos}
f <- paste0("/big/results/bsm/2018-05-09-truth-sets/chr22/check-chaggai/", c("chaggai", "attila"), "/ceph-gp-var.pos")
names(f) <- c("chaggai", "attila")
pos <- lapply(f, scan)
grid.draw(venn.diagram(pos, NULL, cat.cex = 1.4, fill = my.col <- c("blue", "red"), cat.col = my.col))
```

```{r}
tsv <- c("~/projects/bsm/results/2018-05-09-truth-sets/chr22/Tnseq-snps/all.tsv")
l <- import.mybcftools.isec.tsv(tsv)
```
