#! /usr/bin/env bash

# Make variant type-specific truth sets from CEPH/Utah grandparent VCFs.
#
# Inputs
# inputdir: the directory with the 4 grandparental VCFs
# vartype: [snps|indels|...]
#
# Outputs
# The [snps|indels|...] directory---in the same directory as
# inputdir---contains the following files and directories:
# NA12889.vcf.gz,...,NA12892.vcf.gz: the 4 call sets, i.e. grandparental VCFs filtered for vartype
# NA12889.vcf.gz.tbi,...,NA12892.vcf.gz.tbi: the corresponding indices
# variant-alleles: directory for variants distinguished by positions AND alleles
# variant-positions: directory for variants distinguished by ONLY positions
# {variant-alleles,variant-alleles}/{0001, 0011,...,1111}: the 2^4 - 1 = 15 partitions from the 4 call sets

usage="`basename $0` inputdir [snps|indels|mnps|other]"
if test $# -ne 2; then
    echo $usage; exit 1
fi

inputdir=$1
vartype=$2
outputdir="`dirname ${inputdir}`/`basename ${inputdir}`-${vartype}"

# map of chromosome names: from "Illumina platinum format" to "BSMN format"
touch chr-map
chrmap=`realpath chr-map`
for s in {1..22} X Y; do echo -e "chr$s\t$s"; done > $chrmap
echo -e "chrM\tMT" >> $chrmap

touch vcf-header
vcfheader=`realpath vcf-header`
cat > $vcfheader <<EOF
##fileformat=VCFv4.1
##contig=<ID=1,length=249250621>
##contig=<ID=2,length=243199373>
##contig=<ID=3,length=198022430>
##contig=<ID=4,length=191154276>
##contig=<ID=5,length=180915260>
##contig=<ID=6,length=171115067>
##contig=<ID=7,length=159138663>
##contig=<ID=8,length=146364022>
##contig=<ID=9,length=141213431>
##contig=<ID=10,length=135534747>
##contig=<ID=11,length=135006516>
##contig=<ID=12,length=133851895>
##contig=<ID=13,length=115169878>
##contig=<ID=14,length=107349540>
##contig=<ID=15,length=102531392>
##contig=<ID=16,length=90354753>
##contig=<ID=17,length=81195210>
##contig=<ID=18,length=78077248>
##contig=<ID=19,length=59128983>
##contig=<ID=20,length=63025520>
##contig=<ID=21,length=48129895>
##contig=<ID=22,length=51304566>
##contig=<ID=X,length=155270560>
##contig=<ID=Y,length=59373566>
##contig=<ID=MT,length=16569>
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO
EOF

#nthreads="$((`nproc` - 1))" # only minimal speedup
nthreads=0
gparents="NA12889 NA12890 NA12891 NA12892"

# filter for the selected variant type
if test ! -d $outputdir; then
    mkdir $outputdir
    for gp in $gparents; do
        gpvcf="$outputdir/$gp.vcf.gz"
        bcftools annotate --rename-chrs $chrmap --output-type z \
            --threads $nthreads \
            $inputdir/${gp}_S1.vcf.gz |
        # keep only chromosomal contigs
        bcftools view --types $vartype --output-type z \
            --output-file $gpvcf \
            --targets 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,X,Y,MT \
            --threads $nthreads -
        bcftools index --tbi $gpvcf
    done
fi
rm $chrmap

cd $outputdir

mkdir variant-{alleles,positions}
partitions="1000 1100 1010 1001 1110 1101 1011 1111 0100 0110 0101 0111 0010 0011 0001"
for part in $partitions; do
    # variants distinguished by positions AND alleles
    alleles=variant-alleles/$part
    allelesvcf=$alleles.vcf.gz
    bcftools isec --collapse none --output $alleles -n~$part --threads $nthreads NA128*.vcf.gz
    cat $vcfheader $alleles |
    bcftools view --output-file $allelesvcf --output-type z -
    bcftools index --tbi $allelesvcf
    # variants distinguished by ONLY positions
    positions=variant-positions/$part
    bcftools isec --collapse all --output $positions -n~$part --threads $nthreads NA128*.vcf.gz
done

cat variant-alleles/[01][01][01][01] > variant-alleles/variant-alleles
cat variant-positions/[01][01][01][01] > variant-positions/variant-positions
