#! /usr/bin/env bash

input_VCF_file=${1:-`realpath ../NA12892_S1-1.vcf.gz`}
input_chain_file="`realpath $HOME/data/refgenome/mapping/GRCh38_to_GRCh37.chain.gz`"
ref_genome_file=/big/data/refgenome/GRCh37/ensembl/release-75/Homo_sapiens.GRCh37.75.dna.toplevel.fa
output_dir="`realpath $PWD`"
output_file="$output_dir/grch38-grch37.vcf"
CrossMap.py vcf $input_chain_file $input_VCF_file $ref_genome_file $output_file 2> $output_file.log
