#! /usr/bin/env bash

input_VCF_file=${1:-`realpath ../NA12892_S1-1.vcf.gz`}
input_chain_file="`realpath $HOME/data/refgenome/mapping/GRCh37_to_GRCh38.chain.gz`"
ref_genome_file=/big/data/refgenome/GRCh38/ensembl/release-92/Homo_sapiens.GRCh38.dna.primary_assembly.fa
output_dir="`realpath $PWD`"
output_file="$output_dir/grch37-grch38.vcf"
CrossMap.py vcf $input_chain_file $input_VCF_file $ref_genome_file $output_file 2> $output_file.log
