#!/usr/bin/env bash

nproc=8
outdir=/projects/bsm/attila/results/2019-08-02-common-sample-new-alignment

( time multiCaller -p ${nproc} \
    -t Germline \
    -1 Common_7_NeuN.bam \
    -2 Fibro_Common_7.bam \
    -a Common_7_NeuN \
    -b Fibro_Common_7 \
    -o $outdir strelka2Germline2s ) 1>& strelka2Germline2s-run.time &
