#! /usr/bin/env bash
# aggregate .selfSM files of verifyBamID across multiple samples

fname_pattern='\(\(MSSM\|PITT\|PENN\)_[[:digit:]]\+\)_\([^.]\+\)\..*$'
header=`mktemp`
body=`mktemp`


for fname in *.selfSM; do
    indivID=$(echo $fname | sed "s/$fname_pattern/\1/")
    tissue=$(echo $fname | sed "s/$fname_pattern/\3/")
    leftcols=$(echo -ne "$indivID\t$tissue\t")
    rightcols=$(sed 1d $fname)
    echo "$leftcols$rightcols">> $body
    sed 2d $fname >> $header
done

leftcols=$(echo -ne "indivID\ttissue\t")
rightcols=$(sed -n 1p $header)
echo "$leftcols$rightcols" > all.selfSM
cat $body >> all.selfSM
rm $header $body
