#! /usr/bin/env bash

# Annotate VCF with chromatin state from Roadmap Epigenomics project
usage="`basename $0` -b annot.bed -e vcfheader.hdr -c'COL1,...,COLn' [invcf [outvcf]]"
# outvcf is optional; if omitted then data are sent to STDOUT
# If outvcf is omitted then invcf is also optional; if omitted then data
# are read from STDIN

# process options
while getopts "e:b:c:h" opt; do
    case $opt in
        b) bed=$OPTARG;; # BED file
        e) headerfile="$OPTARG";; # header file for VCF
        c) columns="$OPTARG";; # column names for VCF
        h) echo -e $usage 2>&1; exit ;;
    esac
done
shift $(($OPTIND - 1))

invcfarg=${1:-/dev/stdin}
outvcf=${2:-/dev/stdout}

invcf=`tempfile`
intersec=`tempfile`
annotations=`tempfile`

cat $invcfarg > $invcf

bedcols=$(head -n1 $bed | wc -w)
endcol=$(($bedcols + 2))

# intersect BED and VCF
bedtools intersect -wo -a $bed -b $invcf | cut -f4-$(($bedcols + 2)) > $intersec
#bedtools intersect -wo -a $bed -b $invcf | cut -f4-6 > $intersec
# create annotations file for bcftools annotate
paste <(cut -f$(($bedcols - 2))-$(($bedcols - 1)) $intersec) <(cut -f1-$(($bedcols - 3)) $intersec) > $annotations
#paste <(cut -f2-3 $intersec) <(cut -f1 $intersec) > $annotations
# bgzipping and indexing
bgzip $annotations
tabix -s1 -b2 -e2 $annotations.gz
cp $annotations.gz ~/Desktop/annotations.gz
cp $annotations.gz.tbi ~/Desktop/annotations.gz.tbi
# annotate VCF
bcftools annotate --threads=$((`nproc` - 1)) -a $annotations.gz -c $columns -h $headerfile -o $outvcf $invcf

# clean up
rm $invcf $intersec $annotations.gz $annotations.gz.tbi
