#! /usr/bin/env bash

usage="`basename $0` [-t targetdir] invcf sample"

targetdir=$PWD
# process options
while getopts "t:h" opt; do
    case $opt in
        t) targetdir="$OPTARG";;
        h) echo -e $usage 2>&1; exit ;;
    esac
done
shift $(($OPTIND - 1))

invcf=$1
sample=$2

# RESOURCES
# chromatin state from RoadMap project
bed_chrstate="$HOME/projects/bsm/resources/roadmap-epigenomics/chromatin-state/15-state-model/E073_15_coreMarks_stateno-no-chr-prefix.bed"
headerf_chrstate="$HOME/projects/bsm/resources/roadmap-epigenomics/chromatin-state/15-state-model/coreMarks_stateno.hdr"
columns_chrstate='CHROM,POS,INFO/ChromatinState_DLPFC' 
# SiPhy: evol constrained elements
bed_siphy="$HOME/projects/bsm/resources/constrained-elements/SiPhy/elementPartition-annot.bed"
headerf_siphy="$HOME/projects/bsm/resources/constrained-elements/SiPhy/elementPartition-annot.hdr"
columns_siphy='CHROM,POS,INFO/SiPhyLOD,INFO/SiPhyBranchLen'
# szdb CNV
bed_szdb_cnv="$HOME/projects/bsm/results/2020-07-24-szdb/szdb-CNV-cytogenic-band-counts.bed"
headerf_szdb_cnv="$HOME/projects/bsm/results/2020-07-24-szdb/szdb-CNV-cytogenic-band-counts.hdr"
columns_szdb_cnv='CHROM,POS,INFO/szdbCNVcount' 
# CLOZUK GWAS
bed_clozuk_gwas="$HOME/projects/bsm/resources/CLOZUK/gwas.bed"
headerf_clozuk_gwas="$HOME/projects/bsm/resources/CLOZUK/gwas.hdr"
columns_clozuk_gwas='CHROM,POS,INFO/GWASpval' 

# ensure targetdir is different from sourcedir
sourcedir=$(realpath $(dirname $invcf))
if test `realpath $targetdir` ==  $sourcedir; then
    echo "Error: targetdir is the same as sourcedir. Exiting"; exit 1
fi
# make targetdir if necessary
if test -d $targetdir; then
    :
elif test -e $targetdir; then
    echo "Error: targetdir exists but is not a directory. Exiting"; exit 1
else mkdir -p $targetdir
fi

# input/output file types and names
if echo $invcf | grep '\.gz$' >/dev/null; then
    Otype=z
    ext=.vcf.gz
    doindex=true
elif echo $invcf | grep '\.vcf$' >/dev/null; then
    Otype=v
    ext=.vcf
    doindex=false
else
    echo Unexpected file extension.  Exiting; exit
fi
outvcf=$targetdir/`basename $invcf`

bcftools view -Ov $invcf |
~/projects/bsm/src/annotate-vcf-sample $sample |
    ~/projects/bsm/src/annotate-vcf-from-bed -b $bed_chrstate -e $headerf_chrstate -c $columns_chrstate |
    ~/projects/bsm/src/annotate-vcf-from-bed -b $bed_siphy -e $headerf_siphy -c $columns_siphy |
    ~/projects/bsm/src/annotate-vcf-from-bed -b $bed_szdb_cnv -e $headerf_szdb_cnv -c $columns_szdb_cnv |
    ~/projects/bsm/src/annotate-vcf-from-bed -b $bed_clozuk_gwas -e $headerf_clozuk_gwas -c $columns_clozuk_gwas |
    bcftools view -O$Otype -o $outvcf
if $doindex; then bcftools index --tbi $outvcf; fi
