#!/usr/bin/env bash

#Calling this script (without any argument) excises 1, 3, 10, 30, and 100MB long
#subregions from the following BAMs:
#/big/data/bsm/ref-tissue-proj/Fibro_Common_7/Fibro_Common_7_DO16090243-final-all.bam
#/big/data/bsm/ref-tissue-proj/Common_7_NeuN/Common_7_NeuN_DO16090243-final-all.bam

chromA=1
startA="50,000,000"

maindir="$HOME/data/bsm/ref-tissue-proj"

for L in 1 3 10 30 100; do
    for BN in Common_7_NeuN Fibro_Common_7
    do
        inbam="$maindir/$BN/${BN}_DO16090243-final-all.bam"
        "$HOME/projects/bsm/src/aln-subregion" -@ 12 $inbam $L $chromA:$startA
    done
done
