#!/usr/bin/env bash

caseSample=NeuN_pl
controlSample=muscle
while getopts 'a:b:' myopt; do
    case $myopt in
        a) caseSample=$OPTARG;;
        b) controlSample=$OPTARG;;
    esac
done
shift $(($OPTIND - 1))
casebam=$1
controlbam=$2
outdir=$(dirname $casebam)

( time -p myTnseq -p $(nproc) -r $REFSEQ \
    -1 $casebam -2 $controlbam \
    -a Common_7_NeuN \
    -b Fibro_Common_7 \
    -o $outdir ) 1>&$outdir/Tnseq-run.time &
