#!/usr/bin/env bash

length=${1:-3MB}
nproc=${2:-6}
caller=${3:-strelka2Somatic}

rtimef=$length/${nproc}proc/${caller}-run.time

case $caller in
    strelka2*)
        sedcmd='/Elapsed time for full workflow/ { s/.*flow: \([[:digit:]]\+\) sec.*/\1/ ; p }';;
    Tnseq)
        sedcmd='/^overall/ { s/^.*\s\([[:digit:].]\+\) real.*$/\1/ ; p }';;
esac

runtime=$(sed -n "$sedcmd" $rtimef)
echo $length,$nproc,$caller,$runtime
