#! /usr/bin/env bash

# Add GT (genotype) annotation to VCF produced by lofreqSomatic

outputType=v
caseSample=TUMOR
controlSample=NORMAL

while getopts "O:a:b:" opt; do
    case $opt in
        O) outputType=$OPTARG;;
        a) caseSample=$OPTARG;;
        b) controlSample=$OPTARG;;
    esac
done
shift $(($OPTIND - 1))
invcf=$1

usage="usage: `basename $0` [-O v|z] invcf > outvcf"
if test $# -eq 0; then
    echo $usage; exit 0
fi

# temp files for VCF pieces
outvcf=`tempfile`
part1=`tempfile`
format=`tempfile`
sample1=`tempfile`
sample2=`tempfile`

# smaller pieces of output
bcftools view -H $invcf >> $part1
sed 's/.*/GT/' $invcf >> $format
sed 's/.*/0\/0/' $invcf >> $sample1
sed 's/.*/0\/1/' $invcf >> $sample2

# larger pieces of output
bcftools view -h $invcf | sed '/^##FILTER/q' >> $outvcf
echo '##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">' >> $outvcf
bcftools view -h $invcf | sed -n '/^##FILTER/,$ p' | sed -n '2,$ p' >> $outvcf
sed -i "/\(^#CHROM.*$\)/ s//\1\tFORMAT\t$controlSample\t$caseSample/" $outvcf
paste $part1 $format $sample1 $sample2 >> $outvcf

# entire output in desired type; clean-up
bcftools view -O $outputType $outvcf
