#!/usr/bin/env bash

case `hostname` in
    attila-ThinkS)
        main_in="$HOME/projects/bsm/results/calls/ceph-utah/"
        main_out="$HOME/projects/bsm/results/2019-03-18-truth-sets";;
    ada)
        main_in="/projects/bsm/calls/ceph-utah/"
        main_out="/projects/bsm/attila/results/2019-03-18-truth-sets";;
esac

nthread="$((`nproc` - 1))"
preparer=$HOME/projects/bsm/src/prepare4prec-recall

for vartype in snp indel; do
    for gp in NA128{89,90,91,92}; do
        outdir=$main_out/$vartype/individuals/$gp/
        for dataset in chesslab illumina; do
            if test ! -d $outdir; then mkdir -p $outdir; fi
            in=$main_in/$dataset/$gp.vcf.gz
            out=$outdir/$dataset.vcf.gz
            $preparer -O z -P -v $vartype $in > $out
            bcftools index -t $out
        done
        combined=$outdir/combined.vcf.gz
        chessvcf=$outdir/chesslab.vcf.gz
        illumvcf=$outdir/illumina.vcf.gz
        bcftools concat --threads $nthread -a -d all $chessvcf $illumvcf -o $combined -O z 
        bcftools index -t $combined
    done
done
