#! /usr/bin/env bash
outdir=/projects/bsm/attila/results/2020-04-29-sample-fastq-sizes
outfile=$outdir/fastq-nblocks.tsv
echo -e "sample\tnblocks, kB\tfile path" > $outfile
find /projects/bsm/reads -type f -name '*.fq.gz' |
    for fq in `cat`; do
        sample=$(basename $(dirname $fq))
        #sample=$(dirname $fq | sed 's|/projects/bsm/reads/||')
        du_out=$(du $fq | tr -s ' ' '\t')
        echo -e "$sample\t$du_out"
    done >> $outfile
